### PR TITLE
Use reCaptcha api v2

### PR DESCRIPTION
**Pull request by git-commit**
Google recently released an update to their reCaptcha service.
The old api remains working, but it would be nice to use the new api instead.

See: https://developers.google.com/recaptcha/docs/

### CODE REVIEW

**Comment by tommyredz91** [comment]
hey guys, I'm facing this issue with mailchimp plugin: I'm not at all a pc nerd, so hope you all can help me figure this out!
It shows me the following: ERROR: Invalid sitekey

**Comment by davidism** [comment]
@tommyredz91

**Comment by davidism** [comment]
@tommyredz91 you should probably take that up with Mail Chimp customer support.  This isn't that.  This extension has nothing to do with a Mail Chimp plugin, and neither does this specific ticket.  And why did you think calling us "pc nerds" was a good idea?

**Comment by tommyredz91** [comment]
@davidism First of all you actually took it all wrong: if you got harmed by the expression "pc nerd" it's none of my fault, eventually yours, who felt hit by such an expression; second of all I don't need any comment useless as yours; third and last one I will not reply to any quidless useless reply to my comment anymore: if you are touchy, it's none of my problem: sort it out by yourself!

**Comment by davidism** [comment]
Despite that, this still isn't the correct place to ask your question.

**Comment by davidism** [comment]
@tommyredz91 despite all that, this still isn't the place to ask that question.

**Pull request merged**
