### PR TITLE
Add support to change message language

### PR DESCRIPTION
**Pull request by greyli**
With this PR, people can change the built-in error message's default language.

- [x] Test added
- [x] Documentation updated 

Address #303 and #300.

### CODE REVIEW

**Comment by greyli** [comment]
It seems the build error is related to `pytest`. Maybe we should drop support for Python 2.6 and 3.3.

Trackback:
```pytb
Collecting pytest>=3
  Downloading pytest-3.3.1-py2.py3-none-any.whl (184kB)
pytest requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
ERROR: could not install deps ...
```

**Comment by davidism** [comment]
Why can't this be handled with Flask-Babel's `BABEL_DEFAULT_LOCALE` config?

**Comment by davidism** [comment]
To be clear: I don't really understand I18N, so if this is how things are done, ok. But I did try digging into this a while ago and the relationship between Python's `gettext`, Babel for WTForms, and Flask-Babel for Flask-WTF was confusing. It seems like every library requires a different configuration, rather than working together.

**Comment by lepture** [comment]
@davidism I'll review this.

**Comment by greyli** [comment]
@davidism IMO, Babel/Flask-Babel (i18n) allow you to get user's locale dynamically (through user config, request header etc.), then display the corresponding language. This PR make it possible to change built-in error message's default language directly. 

In a nutshell, this PR let you to **hard-coded** the locale, whereas i18n **adapt** locale for different users.

**Comment by davidism** [comment]
I'm still not clear why this is required over `BABEL_DEFAULT_LOCALE`. Also, it seems like unnecessary overhead to get the config and set `self.locales` every time a form is translated, just to skip the translation. Why not override `get_translations` to return the locale you want?

**Comment by greyli** [comment]
People sometimes don't want to enable i18n, they just want to change built-in message's language. You can achieve this with pure WTForms (see docs [here](http://wtforms.readthedocs.io/en/latest/i18n.html#using-the-built-in-translations-provider)).

**Comment by greyli** [comment]
Maybe we can depend on `WTF_I18N_ENABLED`, something like:
```python
def get_translations(self, form):
    if not current_app.config.get('WTF_I18N_ENABLED', True):
        return super(FlaskForm.Meta, self).get_translations(form)
```
Then we can set locale like this:
```python
class MyBaseForm(FlaskForm):
    class Meta:
        locale = ['es']

class NameForm(MyBaseForm):
     ...
```

**Comment by lepture** [comment]
@greyli Yes. I prefer the last one.

**Comment by greyli** [comment]
@lepture Ok, I will do it.

**Comment by lepture** [comment]
@davidism it seems our tools are not supporting Python 2.6 and 3.3 any more.

**Pull request merged**
