### PR TITLE
BUG FIX : csrf.error_handler does not work as documented

### PR DESCRIPTION
**Pull request by Off-IT**

### CODE REVIEW

**Comment by lepture** [comment]
What does this `return` fix?

**Comment by Off-IT** [comment]
it fixes issue #200 
it returns the result of csrf.error_handler instead of None

**Comment by lepture** [comment]
error_handler should raise not return.

**Comment by Off-IT** [comment]
This is not what is documented here https://flask-wtf.readthedocs.org/en/latest/csrf.html#module-flask_wtf.csrf and definitely not backward compatible with previous version 0.11. This breaks all my tests regarding csrf in my project when I updated to version 0.12

```python
@csrf.error_handler
def csrf_error(reason):
    return render_template('csrf_error.html', reason=reason), 400
```

**Comment by davidism** [comment]
#264 deprecated `error_handler`. Use Flask's error handling system with `@app.errorhandler(CsrfError)`. As a temporary measure, custom handlers decorated with `@csrf.error_handler` allow both `return` and `raise`.

**Pull request closed without merging**
