### PR TITLE
Add support for multiple file validation

### LINKED ISSUE #337: Handle multiple files
Now that WTForms 2.2 is released, we need to update our fields and validators to handle multiple files.

### PR DESCRIPTION
**Pull request by greyli**
Add `MultipleFileField`, `FilesRequired`, `FilesAllowed` to support multiple files validation.

Closes #337

### CODE REVIEW

**Comment by davidism** [comment]
I experimented with this back when I made the WTForms PR, I'm trying to remember the design decisions I made.

I think that while the fields were separate so it was clear what was intended, I was trying to make the validators work for both single and multiple files (rather than adding extra validators or a `multiple=True` flag). Do you or @lepture agree with that?

Also might be interesting to add a test of the `Length` validator on the multiple field.

**Comment by greyli** [comment]
Sounds good to me.

**Comment by theomega** [comment]
I'd love to see this merged. Anything I can help with?

**Comment by misilot** [comment]
Any chance of this being merged? :)

**Comment by PanderMusubi** [comment]
> Any chance of this being merged? :)

Hoping the same. @azmeuk can you review this please?

**Comment by greyli** [comment]
This PR may not be merged.

I was planning to implement what [David recommended](https://github.com/wtforms/flask-wtf/pull/338#issuecomment-394225278) as an alternative to this PR in January, but I was too busy with work. Maybe I will have time to make another PR next month. BTW, I'm also happy to review a PR!

**Comment by greyli** [comment]
Hi guys, I finally re-implemented this in #556. With the new PR, the `FileRequired`, `FileAllowed`, and `FileSize` can be used for both single or multiple files.

**Pull request closed without merging**
